use_frameworks!

platform :ios, '9.0'

target 'ZMCategorieKit_Example' do
  pod 'ZMCategorieKit', :path => '../'

  target 'ZMCategorieKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
